name: Move issue to glo column

on:
  issues:
    types: [labeled]

jobs:
  build:
    name: Glo actions
    runs-on: ubuntu-latest
    steps:
    - uses: Axosoft/glo-action-parse-links@v1
      id: glo-parse

    - uses: Axosoft/glo-action-move-card@v1
      with:
        authToken: ${{ secrets.Glo_PAT }}
        cards: '${{ steps.glo-parse.outputs.cards }}'
        column: '${{ github.event.label.name }}'
      id: glo-move
